version: '3.8'

services:
  web:
    build: .
    environment:
      - DEBUG=True
      - DB_NAME=${DB_NAME:-digital_wallet}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=db
      - DB_PORT=5432
      - CREATE_SUPERUSER=True
      - SEED_DB=True
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME:-digital_wallet}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data: